# Generated by Django 2.2.7 on 2019-11-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': '포스',
                'verbose_name_plural': '포스트',
                'ordering': ['title'],
            },
        ),
    ]
